languageCode = "en-us"
title = "We fight with cards - Weekly newsletter about Digital Card Games"
baseURL = "http://wefightwithcards.com/"
theme = "wefight"
publishDir = "docs"
disqusShortname = "wefightwithcards"
